### ISSUE TITLE
module 'ts_context_commentstring.internal' not found

### ISSUE THREAD

**Issue by ahmedkhalf** [winston0410/commented.nvim#11]
When I use the hook provided in the readme, I get a packer compile error:
```
packer.nvim: Error running config for commented.nvim: [string "..."]:0: module 'ts_context_commentstring.internal' not found
```

**Comment by winston0410** [comment]
Can you show your complete setup? Have you lazy loaded any plugin?

**Comment by ahmedkhalf** [comment]
This is my neovim config: https://github.com/ahmedkhalf/RockNvim
All my plugins are loaded on startup.

**Comment by winston0410** [comment]
@ahmedkhalf As I have just checked, you are not using the hook provided by this plugin, which the error cannot be coming from `commented`. Try run `:PackerSync` and `:PackerCompile` and make sure you have installed `ts_context_commentstring`?

**Comment by winston0410** [comment]
Closing this as this should not be related with `commented`.
