### ISSUE TITLE
Unable to uncomment

### ISSUE THREAD

**Issue by s1n7ax** [winston0410/commented.nvim#12]
When there is a space between comment string and the statement
```lua
-- BEFORE
-- print()

-- AFTER
print()
```

When there is no space between comment string and the statement
```lua
-- BEFORE
--print()

-- After
--  --print
```

Commented expects to have a space between comment string and the statement

**Comment by winston0410** [comment]
Good catch, I think this is an upstream issue as the `cms` for Lua has been changed. Fixed in https://github.com/winston0410/commented.nvim/commit/1a68afce1aa9a81f460e30b9ea78d2f0eeee3928
