### ISSUE TITLE
Help wiht defining keybings with the `require('commented').toggle_comment(mode)` function

### ISSUE THREAD

**Issue by becarepsol** [winston0410/commented.nvim#13]
In the docs there is a comment on how to define your own custom mappings with the `require('commented').toggle_comment(mode)` function, but it's not clear on how to pass the arguments.

I've been trying to define my own mapping by setting the `keybindings` options to false and mapping `require('commented').toggle_comment('n')` in normal mode and `require('commented').toggle_comment('v')` for visual mode, yet this has resulted in some unexpected behavior:

Having defined the mapping as such with the plugin `witchkey`:

`ac = {"<cmd>lua require('commented').toggle_comment('n')<cr>", "Comment"}`

Expected behavior:

`ac<motion>`: Comment lines targeted by `<motion>`

Actual result:

`ac<motion>`: Comment the whole file

This same behavior is produced with `require('commented').toggle_comment('v')` when map in the same way but for visual mode

On the other hand, when calling the function `lua require('commented').toggle_comment('c', '<linenumber>', <linenumber>')` in normal mode it works as expected, provided that I give it the exact range of lines, but I don't know how could I map this to a keybinding, nor how to make it work for visual mode

**Comment by winston0410** [comment]
https://github.com/winston0410/commented.nvim/blob/5bf3a65a760589cd62f96289cd3698b8e3eccfb6/lua/commented/init.lua#L263-L274

As I recall from my code, `Commented_n()` is used in `normal` and `visual` mode, and `Commented_nl()` is for commenting whole line in normal mode. Have you tried the default binding, or create the binding without `whichkey`?

**Comment by winston0410** [comment]
Closing this as this is usage issue.

**Comment by petobens** [comment]
Hi! I'm also having a hard time defining custom mappings. AFAICT from the code (not from the readme) we need to use `commented()` instead of `toggle_comment()` now. However if I use:
```lua
vim.api.nvim_set_keymap('n', '<Leader>xx', "v:lua.require'commented'.commented()", {
				expr = true,
				silent = true,
				noremap = true,
			})
```
and press `<Leader>xx` then I need to press and extra key (say 'l') for the comment to actually happen. How can I fix this? Thanks in advance!

**Comment by winston0410** [comment]
@petobens You are right readme is outdated! It would be great if you can help fixing that.

For when you want, you just need to use this:

```lua
vim.api.nvim_set_keymap('n', '<Leader>x', "v:lua.require'commented'.commented_line()", {
				expr = true,
				silent = true,
				noremap = true,
			})
```
