### ISSUE TITLE
Cannot integrate gdscript commenting

### ISSUE THREAD

**Issue by lifer0se** [winston0410/commented.nvim#16]
I've tried adding the following under inline_cms and block_cms (replacing "inline" with "block" for block_cms -- Godot does not support block commenting anyway):

gdscript3 = { inline = "#%s" }
gdscript = { inline = "#%s" }
gd = { inline = "#%s" }

None of them seem to work. My lua knowledge is minimal so.. What am I missing? :)

**Comment by winston0410** [comment]
You should be adding these in the `/ftplugin`. What is the file extension used by Godot? Let me try and add this for you.

**Comment by winston0410** [comment]
@lifer0se Fixed

https://github.com/winston0410/commented.nvim/commit/6d008310d60d5c45bf1b47228b622adbc109d080

**Comment by lifer0se** [comment]
Perfect! Thanks a lot!
