### ISSUE TITLE
nvim builtin commentstring

### ISSUE THREAD

**Issue by dm9pZCAq** [winston0410/commented.nvim#17]
neovim already sets commentstring for many filetypes
https://github.com/neovim/neovim/tree/master/runtime/ftplugin

![pic](https://0x0.st/-RNX.png)

another problems i found in your `ftplugin` files:
- they uses `cms` [abbreviation option](https://github.com/Vimjas/vint/wiki/Vint-linting-policy-summary#style-problem)

also in `c.vim`:
- `c++` style [comments](https://en.cppreference.com/w/c/comment) appears in `C99`, but `c89` don't have it
to fix this you can do something like [this](https://github.com/neovim/neovim/blob/v0.5.1/runtime/doc/syntax.txt#L943):
```vim
if exists('c_no_c99')
	set commentstring=/*%s*/
else
	set commentstring=//%s
endif
```

but it's better to let [neovim do it himself](https://github.com/neovim/neovim/blob/v0.5.1/runtime/ftplugin/c.vim#L24-L26)

**Comment by winston0410** [comment]
Hi thank you for your comment! Indeed Neovim has cms provided for many ft, buy some of those are block types some are inline, which makes calculation difficult. All the `cms` defined are inline, and if that languages support block as well, it will be included in `commented.lua`

Neovim is a very deep software, is there any issue with using `cms`?

**Comment by winston0410** [comment]
Btw thats great for you to point out the `c.vim` issue. I am not a c/cpp dev so I didnt notice it. Do you want to submit a pr? I will accept it

**Comment by dm9pZCAq** [comment]
> Neovim is a very deep software, is there any issue with using cms?

not real issue, it is [for readability](https://rbtnn.hateblo.jp/entry/2014/12/28/010913)

> Do you want to submit a pr?

ok, sure

**Comment by winston0410** [comment]
Closing it as the issue solved for now
