### ISSUE TITLE
Visual Multiline comment with which-key

### ISSUE THREAD

**Issue by petertriho** [winston0410/commented.nvim#2]
Doesn't seem to work when using with https://github.com/folke/which-key.nvim

With `v = "<Leader>c"` when I select multiple lines, it only uses single line comments, with `v = "gc"` multiline comment works fine
e.g. in lua:
`<Leader>c`
```
        -- require("commented").setup({
            -- comment_padding = " ",
            -- keybindings = {n = "gc", v = "<Leader>c", nl = "gcc"},
            -- set_keybinding = true,
            -- ex_mode_cmd = "Comment"
        -- })


```
`gc`
```
        --[[ require("commented").setup({
            comment_padding = " ",
            keybindings = {n = "gc", v = "gc", nl = "gcc"},
            set_keybinding = true,
            ex_mode_cmd = "Comment"
        }) ]]

```

**Comment by winston0410** [comment]
I haven't used `which-key` before, but I guess the mapping has been overlapped and `which-key` has taken that key. Have you tried `:vmap` and check if that key calls function from `commented`?

**Comment by petertriho** [comment]
@winston0410 
vmap is showing
```
v  <Space>c    * Commented_n()
```

With kommentary, multiline comment works fine with the same mapping

**Comment by winston0410** [comment]
@petertriho Showing `v  <Space>c    * Commented_n()` in `vmap` means that the mapping was not hijacked by other plugins. Can you confirm again that it doesn't work?

**Comment by petertriho** [comment]
Yep, still doesn't work

**Comment by winston0410** [comment]
Are you using `space` as your leader key?

**Comment by petertriho** [comment]
Yes I am

**Comment by winston0410** [comment]
I get the issue now, it is because by default I assumed user will use the same key for normal and visual mode, and the mapping is all done in a loop.

It is a easy fix.

**Comment by ibhagwan** [comment]
I also use which-key with the below `commented.nvim` mappings, I am unable to block comments to work, even if I visual-select a single word in the middle of the line I get a line comment instead of block.

My setup function:
```lua
    use { 'winston0410/commented.nvim',
        config = function() require('commented').setup({
          keybindings = {n = "gc", v = "gc", nl = "gcc"},
        }) end
    }
```

Output of `:nmap gc`:
```lua
n  g           * <Cmd>lua require("which-key").show("g", {mode = "n", auto = true})<CR>
n  gcc         * Commented_nl()
n  gc          * Commented_n()
```

Output of `vmap gc`:
```lua
x  g           * <Cmd>lua require("which-key").show("g", {mode = "v", auto = true})<CR>
v  gc          * Commented_n()
```

**Comment by winston0410** [comment]
@ibhagwan Do you mind posting your `which-key` setup as well? I will try and reproduce the issue you have.

**Comment by ibhagwan** [comment]
> @ibhagwan Do you mind posting your `which-key` setup as well? I will try and reproduce the issue you have.

My which-key setup [is published here](https://github.com/ibhagwan/nvim-lua/blob/main/lua/plugin/which_key.lua) as part of my [complete nvim setup](https://github.com/ibhagwan/nvim-lua).

**Comment by winston0410** [comment]
@ibhagwan I have just tried out your setting, and it just worked. And this is my output of `:nmap gc`:

```
n  g           * <Cmd>lua require("which-key").show("g", {mode = "n", auto = true})<CR>
n  gcc         * Commented_nl()
n  gc          * Commented_n()
```

`vmap gc`
```
x  g           * <Cmd>lua require("which-key").show("g", {mode = "v", auto = true})<CR>
v  gc          * Commented_n()
```

**Comment by ibhagwan** [comment]
> @ibhagwan I have just tried out your setting, and it just worked. And this is my output of `:nmap gc`:
> 
> ```
> n  g           * <Cmd>lua require("which-key").show("g", {mode = "n", auto = true})<CR>
> n  gcc         * Commented_nl()
> n  gc          * Commented_n()
> ```
> 
> `vmap gc`
> 
> ```
> x  g           * <Cmd>lua require("which-key").show("g", {mode = "v", auto = true})<CR>
> v  gc          * Commented_n()
> ```

Strange, this is exactly my output.

Just to be clear, when I visual line a couple of lines in a .lua file and press `gc` that should use block comment or am I misunderstanding when block comment is chosen?

**Comment by winston0410** [comment]
@ibhagwan Oh I got you now. Right now this plugin is default to use **inline** comment for **commenting**, and it can handle **inline** and **block** comment for **uncommenting**. I plan to add the feature of using block comment for commenting next, so your setup right now is totally alright.

**Comment by petertriho** [comment]
Oh, that makes sense now. Had another plugin installed that was mapped to gc, so block comment appeared to be working for gc but not for <leader>c

**Comment by winston0410** [comment]
@ibhagwan @petertriho I have just committed, if you need to use line comment on single line, and block comment on multiple line, you can try this now:

```lua
require("commented").setup({
	prefer_block_comment = true
})
```

**Comment by petertriho** [comment]
Perfect! Thanks

**Comment by ibhagwan** [comment]
> @ibhagwan @petertriho I have just committed, if you need to use line comment on single line, and block comment on multiple line, you can try this now:
> 
> ```lua
> require("commented").setup({
> 	prefer_block_comment = true
> })
> ```

Ty! 🙏
