### ISSUE TITLE
Commenting C code doesn't really work

### ISSUE THREAD

**Issue by cryptomilk** [winston0410/commented.nvim#4]
Hi,

I've just tried your plugin, but it doesn't really work with C code:

![commented](https://user-images.githubusercontent.com/545480/126748903-bd28a35d-b9cb-4ab9-b7f8-7dc817767666.png)

Code:

```c
bool samba_cmdline_init_common(TALLOC_CTX *mem_ctx)
{
        bool ok;

        ok = samba_cmdline_set_talloc_ctx(mem_ctx);
        if (!ok) {
                return false;
        }

        fault_setup();

        /*
         * Log to stdout by default.
         * This can be changed to stderr using the option: --debug-stdout
         */
        setup_logging(getprogname(), DEBUG_DEFAULT_STDERR);

        talloc_set_log_fn(_samba_cmdline_talloc_log);
        talloc_set_abort_fn(smb_panic);

        return true;
}
```

Commented out with commented.nvim:

```c
/* bool samba_cmdline_init_common(TALLOC_CTX *mem_ctx) */
/* { */
        /* bool ok; */
 */
        /* ok = samba_cmdline_set_talloc_ctx(mem_ctx); */
        /* if (!ok) { */
                /* return false; */
        /* } */
 */
        /* fault_setup(); */
 */
        /* /* */
         /* * Log to stdout by default. */
         /* * This can be changed to stderr using the option: --debug-stdout */
         /* */ */
        /* setup_logging(getprogname(), DEBUG_DEFAULT_STDERR); */
 */
        /* talloc_set_log_fn(_samba_cmdline_talloc_log); */
        /* talloc_set_abort_fn(smb_panic); */
 */
        /* return true; */
/* } */
```

Feature Request: For C/C++ it would be nice if it would be possible to tell commented.nvim to comment out using `#if 0`:

```c
#if 0
/* i = 5 */
int i = 5;
#endif
```

for commenting out code :-)

**Comment by winston0410** [comment]
Thank you for reporting, and I will have to test why for the issue.

For the feature request, I am not familiar with c/cpp. Is `#if 0` `#endif` a docstring, or something that always evaluate to false? Why don't you comment out block with `/* */` instead?

Anyway the option to decide which pattern to comment out is provided, yet it is not documented. That would be a easy fix i guess.

**Comment by cryptomilk** [comment]
The reason is that a comment block within a comment block is not allowed.

This is invalid:
```c
/*
/* test */
*/
```

`#if 0` is handled by the pre-processor of the compiler. It will just throw away the code. It is a nice way to comment something out.

**Comment by winston0410** [comment]
Oh I see. So to add a new pattern for uncomment, you just need to add it like this: https://github.com/winston0410/commented.nvim/commit/53d2854cd714593aa55ceed8bd3b4e095d2250e2

But now it shouldn't work for commenting and uncommenting your example of this, as this plugin only support inline comment toggling at the moment(And I want to add in the feature of block commenting as well).

```cpp
#if 0
/* i = 5 */
int i = 5;
#endif
```

**Comment by winston0410** [comment]
@cryptomilk If you need to define a comment symbol to use , you can do this:

```lua
require "commented".setup {
  cms_to_use = {
     cpp = "#if 0%s#endif"
  }
}
```

**Comment by cryptomilk** [comment]
If I add that I get:

`commented.nvim/lua/commented/helper.lua:40: attempt to index local 'cs' (a nil value)`

Selecting something in VISUAL LINE mode ...

**Comment by winston0410** [comment]
@cryptomilk Just remove the code I mentioned in the previous comment. I have just made a large commit, and now you should be able to uncomment that block of code.

Meanwhile, it still needs some work for making multiline comment with block comment symbols works tho.

**Comment by winston0410** [comment]
@cryptomilk Update to the latest commit and try this now, it should do exactly what you want:)

```lua
require("commented").setup({
                prefer_block_comment = true,
                custom_cms = {
                    cpp = {
                        block = "#if 0%s#endif"
                    }
                }
})
```

**Comment by cryptomilk** [comment]
Thank you very much! Very nice.

Once last question: How do I get a newline after `#if 0` and  after `%s`? :-)

**Comment by winston0410** [comment]
@cryptomilk That is definitely not supported right now, and PR welcomed!:) I guess you just need an option, and insert extra empty line before and after `lines` 

https://github.com/winston0410/commented.nvim/blob/291295e05c9fcafa3d1659c5a430e7b0e548ee76/lua/commented/init.lua#L134-L143

**Comment by cryptomilk** [comment]
I'm not fluent in lua, but the only working solution I found is:

```diff
diff --git a/lua/commented/init.lua b/lua/commented/init.lua
index 53b2beb..f11b38a 100644
--- a/lua/commented/init.lua
+++ b/lua/commented/init.lua
@@ -134,8 +134,22 @@ end
 
 local function toggle_block_comment(lines, start_line, end_line, block_symbols, should_comment)
        if should_comment then
+               local str = ''
+
                lines[1] = lines[1]:gsub("([^%s]*)", block_symbols[1][1] .. opts.comment_padding .. "%1", 1)
+
+               str = lines[1]
+               i, j = string.find(str, block_symbols[1][1])
+               lines[1] = string.sub(str, i, j)
+               table.insert(lines, 2, string.sub(str, j + 1, #str))
+
                lines[#lines] = lines[#lines]:gsub("%s*$", "%1" .. opts.comment_padding .. block_symbols[2][2], 1)
+
+               str = lines[#lines]
+               i, j = string.find(str, block_symbols[2][2])
+               lines[#lines] = string.sub(str, 0, i - 1)
+               table.insert(lines, #lines + 1, string.sub(str, i, j))
+
                vim.api.nvim_buf_set_lines(0, start_line, end_line, false, lines)
        else
                lines[1], lines[#lines] = unpack(clear_lines_symbols({ lines[1], lines[#lines] }, block_symbols))
```

How we need an option, to only insert new lines if wanted per language ...
