### ISSUE TITLE
Block un-comment messes up formatting

### ISSUE THREAD

**Issue by ibhagwan** [winston0410/commented.nvim#5]
uncommenting a block comment moves the first and last lines of the block comment to the start of the line.

To reproduce, comment say 3 lines in block mode and then use visual mode to selected the commented lines and press `gc` to uncomment, the first and last lines move to col 0 instead of staying where they were before commenting.

**Comment by winston0410** [comment]
Fixed with the latest commit

**Comment by ibhagwan** [comment]
Ty!
