### ISSUE TITLE
Do we still need commented.vim?

### ISSUE THREAD

**Issue by ahmedkhalf** [winston0410/commented.nvim#8]
Neovim 0.5 stable supports plugin/commented.lua

**Comment by winston0410** [comment]
@ahmedkhalf Thank you for the issue. I think you are correct that `commented.vim` can be replaced with `commented.lua`, but I am currently busy with my work so I won't make the switch right now. It will be great if you can do that and submit a PR. 👍

**Comment by ahmedkhalf** [comment]
Sure, will do in a few hours

**Comment by winston0410** [comment]
@ahmedkhalf thank you so much

**Comment by ahmedkhalf** [comment]
Sorry, I don't think I am committed enough to this. I started using lunarvim a day after my commitment because configuring neovim was taking too long. So sorry, but we'll have to pass this to someone else, or close the issue.

**Comment by winston0410** [comment]
yes configuring neovim is never easy. No problem at all!

**Comment by winston0410** [comment]
I have some partial success, but I am not sure how to remove the `opfunc` function there yet:

https://github.com/winston0410/commented.nvim/commit/de2b976b5eec344304ac09532ba0c046a01852d9

**Comment by winston0410** [comment]
Done!

https://github.com/winston0410/commented.nvim/commit/3bc239cd8ac30c99ca708ac209325ce6a0c92764
